### ISSUE TITLE
File picker doesn't work in anything other than Chome, Edge and Opera

### ISSUE THREAD

**Issue by A1ex-N** [grabofus/zomboid-chunk-cleaner#2]
because of the use of window.showDirectoryPicker() you can't open the directory picker unless you use Chrome, Edge or Opera. A message telling users the site won't work unless you use a supported browser, or just supporting the other browsers using a different method to load a directory would be good.

https://developer.mozilla.org/en-US/docs/Web/API/Window/showDirectoryPicker

**Comment by grabofus** [comment]
Hi @A1ex-N, thanks for reporting the issue, I've added an alert for browsers that do not support the feature

![image](https://user-images.githubusercontent.com/34451173/233145360-bf5f4f7a-a9c5-4b25-b0bc-569a76379925.png)
