### ISSUE TITLE
Requested functionality

### ISSUE THREAD

**Issue by Kafkatrap** [grabofus/zomboid-chunk-cleaner#3]
Hi, first off i want to thank you for making this tool. 

Would it be possible to implement the option to prevent player safehouse chunks from being wiped, or maybe an easier solution would be to allow multiple chunks to be selected?
Meaning basically having the ability to clear the entire map except multiple player safehouse chunks.

**Comment by grabofus** [comment]
@Kafkatrap it sounds like an interesting feature to add, do you know by any chance where safehouse data is kept within the save folder?

**Comment by Kafkatrap** [comment]
@grabofus i don't know anything about this, but i think they are saved somewhere in the map_zone.bin files?

**Comment by grabofus** [comment]
@Kafkatrap I've found the safehouses in `map_meta.bin` and released a new version. Would you be able to test it and let me know if it worked for you? (as usual please create a backup before using the tool)

![image](https://user-images.githubusercontent.com/34451173/233144962-d73be141-3453-4acf-ac2c-2b15ddcd0a3c.png)
