### ISSUE TITLE
Unable to use on a network server

### ISSUE THREAD

**Issue by TraceIronworks** [grabofus/zomboid-chunk-cleaner#6]
Just curious if there was any way I could set this up on my host box as I cant seem to get the website to pull the info from an ftp link?
As is I need to download my ~10Gb map file, wipe sections, zip upload unpack. Is there any easier way to have this on the host?
Thanks so much for this even if I need to do it the long way!

**Comment by grabofus** [comment]
You can clone and run the repo locally, but I dont think it will help you since it'll still be browser based.

**Comment by TraceIronworks** [comment]
I was worried that might be the issue, I appreciate the reply though!

edit: I did keep trying to select the ftp address from the folder select menu but windows didnt like that idea lol.
